# Use the official Python base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project directory into the container
COPY . .

# Set the entrypoint to run the Python script
CMD ["python", "app/main.py", "Hello, World!"]
